version: '3.4'

services:
  
  publicapigw:     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
    ports:
      - "5200:80"
    volumes:
      - ./src/Gateways/Public:/app/configuration
  
  privateapigw: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
    ports:
    - "5201:80"
    volumes:
      - ./src/Gateways/Private:/app/configuration