version: '3.4'

services:
  basketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  publicapigw:     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
    ports:
      - "5200:80"
    volumes:
      - ./src/Gateways/Public:/app/configuration
  
  privateapigw: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
    ports:
    - "5201:80"
    volumes:
      - ./src/Gateways/Private:/app/configuration